
import { NavbarProperties } from './properties';
import { TouchableOpacity, View } from 'react-native';
import { Icon } from '@rneui/themed';


const Module = {


    /**
     * Navbar(navigation, active);
     *  Overall Application Behavior
     * 
     *  @param {Navigation} navigation - Object generated by react native
     *  @param {active} active - Active tab key (navigation, home, account, etc)
     */
    Navbar: (navigation, active) => {

        const addItem = (icon, target) => {
            return (
                <TouchableOpacity style={NavbarProperties.item} onPress={() => navigation.navigate(target)}>
                    <Icon name={icon} type='feather' color={ target.toLowerCase() == active ? '#1A58A2' : '#808080'} style={NavbarProperties.icon} />
                </TouchableOpacity>
            )
        }
    
        return (

            <View style={NavbarProperties.view}>
            
                {   addItem("home", "Home") }

                {   addItem("bell", "Notification") }

                {   addItem("user", "Account")  }

            </View>
            
        )

    }
    

}

exports.Module = Module;
